(part "BM02B-PASS-1-TFT_LF__SN_"
    (packageRef "BM02BPASS1TFTLFSN")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "MP1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "MP2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "JST (JAPAN SOLDERLESS TERMINALS)")
    (property "Manufacturer_Part_Number" "BM02B-PASS-1-TFT(LF)(SN)")
    (property "Mouser_Part_Number" "306-2BPASS1TFTL")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/JST-Commercial/BM02B-PASS-1-TFTLFSN?qs=QpmGXVUTftFq0jcCuJWPXg%3D%3D")
    (property "Arrow_Part_Number" "BM02B-PASS-1-TFT(LF)(SN)")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/bm02b-pass-1-tft-lf-sn/jst-manufacturing?region=europe")
    (property "Description" "1x2P 2P PA Tin 2 -25~+85 3A 1 2mm Brass Alloy Standing paste SMD,P=2mm Wire To Board Connector ROHS")
    (property "Datasheet_Link" "https://www.jst-mfg.com/product/pdf/eng/ePA-F.pdf")
    (property "symbolName1" "BM02B-PASS-1-TFT_LF__SN_")
)
