name: Generate TOC
on:
  push:
    branches: [ main ]
    paths: [ 'README.md' ]

permissions:
  contents: write

jobs:
  generate-toc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate TOC
        uses: technote-space/toc-generator@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_PATHS: 'README.md'
          TOC_TITLE: '## Table of Contents'
          OPENING_COMMENT: '<!-- TOC -->'
          CLOSING_COMMENT: '<!-- /TOC -->'
          COMMIT_MESSAGE: 'docs: update table of contents'
          MAX_HEADER_LEVEL: 4