name: Auto Generate TOC
on:
  push:
    branches: [ main ]
    paths: [ 'README.md' ]

permissions:
  contents: write

jobs:
  generate-toc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate TOC
        uses: technote-space/toc-generator@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_PATHS: 'README.md'
          TOC_TITLE: '## 目录'
          FOLDING: false
          MAX_HEADER_LEVEL: 6
          COMMIT_MESSAGE: 'docs: auto update TOC'
          COMMIT_NAME: 'github-actions[bot]'
          COMMIT_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'